#!/usr/bin/env node

import { spawn, execSync } from 'node:child_process';
import path from 'path';

const __dirname = import.meta.dirname;
const dir = __dirname

const binDir = `${dir}/node_modules/.bin`;
const viteBin = `${binDir}/vite`;

const port = 8888;

execSync('node ./utils/listingComponent.js', {
	cwd: `${dir}`,
	stdio: 'inherit',
});
execSync('node ./utils/listingPageForRoute.js', {
	cwd: `${dir}`,
	stdio: 'inherit',
});
execSync('node ./utils/listingPluginHeaders.js', {
	cwd: `${dir}`,
	stdio: 'inherit',
});
//execSync('node ./utils/listingPluginComponent.mjs');
//execSync('node ./utils/listingPluginHeaders.mjs');
execSync(`${viteBin} --host --port ${port}`, {
	cwd: `${dir}`,
	stdio: 'inherit',
});
